services:
  mqtt-broker:
    build: .
    ports:
      - "1883:1883"
    networks:
      - db
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
      POSTGRES_DB: meshtastic
    volumes:
      - db:/data/postgres
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  db:
    driver: bridge

volumes:
  db: